### ISSUE TITLE
Could you please provide the performance of downstream tasks like coco?

### ISSUE THREAD

**Issue by mitming** [facebookresearch/asym-siam#3]

**Comment by endernewton** [comment]
Thanks! We have not tested on COCO, on VOC we see some improvements from time to time but the improvement is nos systematic.

**Comment by mitming** [comment]
> Thanks! We have not tested on COCO, on VOC we see some improvements from time to time but the improvement is nos systematic.

Thanks for your answer, does this mean that the asymmetric designs, while beneficial for linear evaluation, are not necessarily effective for downstream tasks like detection and segmentation?

**Comment by wang3702** [comment]
We do not observe clear improvement for downstream tasks on VOC. But we also did not see any decrease in downstream tasks.

**Comment by mitming** [comment]
> We do not observe clear improvement for downstream tasks on VOC. But we also did not see any decrease in downstream tasks.

Thanks a lot!
