### ISSUE TITLE
Question about Multi-crop augmentation

### ISSUE THREAD

**Issue by DerrickWang005** [facebookresearch/asym-siam#6]
Hi Xinlei,

Thanks for your insightful work! I have a question about the Multi-crop augmentation. If encoder_q only sees mini-crop images, will that cause the degeneration of the transfer performance? Besides, could you please show the training log of the multi-crop version? I'm curious of the training acc@1. I'm looking forward to your reply :）

Best wishes,
Zhaoqing

**Comment by haooooooqi** [comment]
Hi Zhaoqing,

(This is Haoqi)
The encoder_q does not only see mini-crops, but also regular crops. You might want to double check the MultiCrop section of our paper.
<img width="536" alt="Screen Shot 2022-05-09 at 6 06 50 PM" src="https://user-images.githubusercontent.com/3500423/167522452-0a41d140-bee0-4276-92df-ba479aef55c4.png">
You may also check the SwAV paper to get one more data point on the multi-crop protocal.

Thanks,
