### ISSUE TITLE
Pretraining on larger datasets like ImageNet-21k

### ISSUE THREAD

**Issue by liming-ai** [facebookresearch/asym-siam#7]
I'm trying to do self-supervised pre-training on a larger dataset (i.e., ImageNet-21k), but it doesn't work well with the existing hyper-parameters. Could you give me some advice on tuning parameters?

**Comment by haooooooqi** [comment]
Hi @mitming 

In the paper we did not have systematical exploration on larger scale datasets. 
Based on our experience, we don't see our proposed methods behave fundamental differently while scaling, hence we don't expect significant effort on tuning the hyper-parameters.

Thanks,
Haoqi
