### ISSUE TITLE
Questions about variance reference

### ISSUE THREAD

**Issue by lee15253** [facebookresearch/asym-siam#8]
Hello, thank you for your insightful work and for releasing your code. I have a few questions about the variance reference:

1. The variance reference of the baseline is 8.2. Did you use the augmentation https://github.com/facebookresearch/asym-siam/blob/bb70f5f86818545f313a7d8b981405d2830aa7b6/main_moco.py#L379-L390
to calculate this value (augementing the data 32 times with this augmetation)?

2. The variance reference of MultiCrop is 38.0. Are the following procedures correct? 
2.1 Load the pre-trained baseline encoder with 800 episodes (with the above default augmentation).
2.2 Feed the encoder with the 32 multi-cropped inputs (using the augmentation mentioned here:)
https://github.com/facebookresearch/asym-siam/blob/bb70f5f86818545f313a7d8b981405d2830aa7b6/main_moco.py#L437-L448)
2.3 Compare 32 outputs of the encoder.
Did I misunderstood something?

3. Could you please explain the procedure of calculating 4.2 for mean encoding in Section 4.5, in case of n=2 (i.e., averaged from 2 separate encodings)?

Thanks again!

**Comment by wang3702** [comment]
First, we already include our calculation details in our paper 
```
We use ImageNet val set (50k images in total), r=32 views, and the 800-ep pre-trained baseline source encoder for variance calculation. Encodings are L2 normalized. To fully mimic the pre-training setting, we use online per-batch statistics for BN, not recorded moving average ones from the training set
```

1 Yes. For baseline, we simply use the default settings.
2 For multi-crop, I think you are correct. If I remember correctly, we calculated variance for the mean embeddings of the multi-crop output of each image.
3 please see my descriptions attached above.

**Comment by lee15253** [comment]
Thank you!
